# ------------------------------------------------------------
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
# ------------------------------------------------------------

name: dapr-helm-to-acr

on:
  push:
    branches:
      - master

jobs:
  test-e2e:
    name: helm chart upload
    runs-on: ubuntu-latest
    env:
      GOVER: 1.14
      GOOS: linux
      GOARCH: amd64
      GOPROXY: https://proxy.golang.org
      SP_APP_ID: ${{ secrets.SP_APP_ID }}
      SP_PASSWD: ${{ secrets.SP_PASSWD }}
      SP_TENANT_ID: ${{ secrets.SP_TENANT_ID }}
      DAPR_REGISTRY: ${{ secrets.DOCKER_TEST_REGISTRY }}
      DAPR_TEST_REGISTRY: ${{ secrets.DOCKER_TEST_REGISTRY }}
      HELMVER: v3.0.3
      DAPR_NAMESPACE: dapr-tests
      MAX_TEST_TIMEOUT: 5400
    steps:
      - name: Set up Go ${{ env.GOVER }}
        uses: actions/setup-go@v2-beta
        with:
          go-version: ${{ env.GOVER }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          repository: ${{ env.CHECKOUT_REPO }}
          ref: ${{ env.CHECKOUT_REF }}
      - name: Set up Helm ${{ env.HELMVER }}
        uses: azure/setup-helm@v1
        with:
          version: ${{ env.HELMVER }}
      - name: Login Azure
        run: |
          az login --service-principal -u 31450916-f863-4c27-88ac-501d63de1a36 -p 131d28c6-9fbd-4eff-8aab-6d458b52df2a --tenant 72f988bf-86f1-41af-91ab-2d7cd011db47 --output none
      - name: Upload Helm charts to ACR
        run: |
          make upload-helmchart-acr
