# ------------------------------------------------------------
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
# ------------------------------------------------------------

name: dapr-helm-to-acr

on:
  push:
    branches:
      - master

jobs:
  test-e2e:
    name: helm chart upload
    runs-on: ubuntu-latest
    env:
      GOVER: 1.14
      GOOS: linux
      GOARCH: amd64
      GOPROXY: https://proxy.golang.org
      HELM: helm
      RELEASE_NAME: dapr
      DAPR_VERSION: 0.7.1
      HELM_CHART_ROOT: ./charts/dapr
      DAPR_REGISTRY: ${{ secrets.DOCKER_TEST_REGISTRY }}
      DAPR_TEST_REGISTRY: ${{ secrets.DOCKER_TEST_REGISTRY }}
      HELMVER: v3.0.3
      DAPR_NAMESPACE: dapr-tests
      MAX_TEST_TIMEOUT: 5400
    steps:
      - name: Set up Go ${{ env.GOVER }}
        uses: actions/setup-go@v2-beta
        with:
          go-version: ${{ env.GOVER }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          repository: ${{ env.CHECKOUT_REPO }}
          ref: ${{ env.CHECKOUT_REF }}
      - name: Set up Helm ${{ env.HELMVER }}
        uses: azure/setup-helm@v1
        with:
          version: ${{ env.HELMVER }}
      - name: Login Azure
        run: |
          az login --service-principal -u ${{ secrets.SP_APP_ID }} -p ${{ secrets.SP_PASSWD }} --tenant ${{ secrets.SP_TENANT_ID }} --output none
      - name: Upload Helm charts to ACR
        run: |
          `export HELM_EXPERIMENTAL_OCI=1`
          `echo ${{ secrets.SP_PASSWD }} | helm registry login ${{ secrets.ACR_NAME }} --username ${{ secrets.SP_APP_ID }} --password-stdin`
          `helm chart save ${{ env.HELM_CHART_ROOT }} ${{ secrets.ACR_NAME }}/${{ HELM }}/${{ env.RELEASE_NAME }}:${{ env.DAPR_VERSION }}`
          `helm chart push ${{ secrets.ACR_NAME }}/${{ HELM }}/${{ env.RELEASE_NAME }}:${{ env.DAPR_VERSION }}`
